# AppVeyor build configuration for JavaScript project
version: 1.0.{build}

image: Visual Studio 2017
environment:
  nodejs_version: "Stable"
  PYTHON: "C:\\Python36-x64"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

platform: Any CPU
configuration: Release

init:
- tzutil /s "UTC"

# Install Node 8
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%JAVA_HOME%\bin;%PATH%

# Projects
clone_depth: 1
branches:
  only:
  - master
  - java-testing

build:
  parallel: true

build_script:
- cmd: >-
    cd Java\

    mvn test

# disable automatic tests
test: off

