// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.microsoft.recognizers.text.datetime.resources;

import java.util.Map;

import com.google.common.collect.ImmutableMap;

public class BaseDateTime {

    public static final String HourRegex = "(?<hour>00|01|02|03|04|05|06|07|08|09|0|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|1|2|3|4|5|6|7|8|9)(h)?";

    public static final String MinuteRegex = "(?<min>00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)";

    public static final String DeltaMinuteRegex = "(?<deltamin>00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)";

    public static final String SecondRegex = "(?<sec>00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)";

    public static final int MinYearNum = 1500;

    public static final int MaxYearNum = 2100;

    public static final int MaxTwoDigitYearFutureNum = 30;

    public static final int MinTwoDigitYearPastNum = 70;

    public static final Map<String, Long> DayOfMonthDictionary = ImmutableMap.<String, Long>builder()
        .put("01", 1L)
        .put("02", 2L)
        .put("03", 3L)
        .put("04", 4L)
        .put("05", 5L)
        .put("06", 6L)
        .put("07", 7L)
        .put("08", 8L)
        .put("09", 9L)
        .put("1", 1L)
        .put("2", 2L)
        .put("3", 3L)
        .put("4", 4L)
        .put("5", 5L)
        .put("6", 6L)
        .put("7", 7L)
        .put("8", 8L)
        .put("9", 9L)
        .put("10", 10L)
        .put("11", 11L)
        .put("12", 12L)
        .put("13", 13L)
        .put("14", 14L)
        .put("15", 15L)
        .put("16", 16L)
        .put("17", 17L)
        .put("18", 18L)
        .put("19", 19L)
        .put("20", 20L)
        .put("21", 21L)
        .put("22", 22L)
        .put("23", 23L)
        .put("24", 24L)
        .put("25", 25L)
        .put("26", 26L)
        .put("27", 27L)
        .put("28", 28L)
        .put("29", 29L)
        .put("30", 30L)
        .put("31", 31L)
        .build();

    public static final Map<String, String> VariableHolidaysTimexDictionary = ImmutableMap.<String, String>builder()
        .put("fathers", "-06-WXX-7-3")
        .put("mothers", "-05-WXX-7-2")
        .put("thanksgiving", "-11-WXX-4-4")
        .put("martinlutherking", "-01-WXX-1-3")
        .put("washingtonsbirthday", "-02-WXX-1-3")
        .put("canberra", "-03-WXX-1-1")
        .put("labour", "-09-WXX-1-1")
        .put("columbus", "-10-WXX-1-2")
        .put("memorial", "-05-WXX-1-4")
        .build();
}
