// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.microsoft.recognizers.text.datetime.resources;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.common.collect.ImmutableMap;

public class ChineseDateTime {

    public static final String MonthRegex = "(?<month>正月|一月|二月|三月|四月|五月|六月|七月|八月|九月|十月|十一月|十二月|01月|02月|03月|04月|05月|06月|07月|08月|09月|10月|11月|12月|1月|2月|3月|4月|5月|6月|7月|8月|9月|大年)";

    public static final String DayRegex = "(?<day>01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|1|2|3|4|5|6|7|8|9)";

    public static final String DateDayRegexInChinese = "(?<day>初一|三十|一日|十一日|二十一日|三十一日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|一日|十一日|十日|二十一日|二十日|三十一日|三十日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|十日|二十日|三十日|10日|11日|12日|13日|14日|15日|16日|17日|18日|19日|1日|20日|21日|22日|23日|24日|25日|26日|27日|28日|29日|2日|30日|31日|3日|4日|5日|6日|7日|8日|9日|一号|十一号|二十一号|三十一号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|一号|十一号|十号|二十一号|二十号|三十一号|三十号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|十号|二十号|三十号|10号|11号|12号|13号|14号|15号|16号|17号|18号|19号|1号|20号|21号|22号|23号|24号|25号|26号|27号|28号|29号|2号|30号|31号|3号|4号|5号|6号|7号|8号|9号)";

    public static final String DayRegexNumInChinese = "(?<day>一|十一|二十一|三十一|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|一|十一|十|二十一|二十|三十一|三十|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|十|二十|廿|卅)";

    public static final String MonthNumRegex = "(?<month>01|02|03|04|05|06|07|08|09|10|11|12|1|2|3|4|5|6|7|8|9)";

    public static final String TwoNumYear = "50";

    public static final String YearNumRegex = "(?<year>((1[5-9]|20)\\d{2})|2100)";

    public static final String YearRegex = "(?<year>(\\d{2,4}))";

    public static final String ZeroToNineIntegerRegexChs = "[一二三四五六七八九零壹贰叁肆伍陆柒捌玖〇两千俩倆仨]";

    public static final String DateYearInChineseRegex = "(?<yearchs>({ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}))"
            .replace("{ZeroToNineIntegerRegexChs}", ZeroToNineIntegerRegexChs);

    public static final String WeekDayRegex = "(?<weekday>周日|周天|周一|周二|周三|周四|周五|周六|星期一|星期二|星期三|星期四|星期五|星期六|星期日|星期天|礼拜一|礼拜二|礼拜三|礼拜四|礼拜五|礼拜六|礼拜日|礼拜天)";

    public static final String LunarRegex = "(农历|初一|正月|大年)";

    public static final String DateThisRegex = "(这个|这一个|这|这一|本){WeekDayRegex}"
            .replace("{WeekDayRegex}", WeekDayRegex);

    public static final String DateLastRegex = "(上一个|上个|上一|上|最后一个|最后)(的)?{WeekDayRegex}"
            .replace("{WeekDayRegex}", WeekDayRegex);

    public static final String DateNextRegex = "(下一个|下个|下一|下)(的)?{WeekDayRegex}"
            .replace("{WeekDayRegex}", WeekDayRegex);

    public static final String SpecialDayRegex = "(最近|前天|后天|昨天|明天|今天|今日|明日|昨日|大后天|大前天)";

    public static final String SpecialDayWithNumRegex = "^[.]";

    public static final String WeekDayOfMonthRegex = "((({MonthRegex}|{MonthNumRegex})的\\s*)(?<cardinal>第一个|第二个|第三个|第四个|第五个|最后一个)\\s*{WeekDayRegex})"
            .replace("{MonthRegex}", MonthRegex)
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{WeekDayRegex}", WeekDayRegex);

    public static final String DateThisRe = "这个|这一个|这|这一|本|今";

    public static final String DateLastRe = "上个|上一个|上|上一|去";

    public static final String DateNextRe = "下个|下一个|下|下一|明";

    public static final String SpecialDate = "(?<thisyear>({DateThisRe}|{DateLastRe}|{DateNextRe})年)?(?<thismonth>({DateThisRe}|{DateLastRe}|{DateNextRe})月)?{DateDayRegexInChinese}"
            .replace("{DateThisRe}", DateThisRe)
            .replace("{DateLastRe}", DateLastRe)
            .replace("{DateNextRe}", DateNextRe)
            .replace("{DateDayRegexInChinese}", DateDayRegexInChinese);

    public static final String DateUnitRegex = "(?<unit>年|个月|周|日|天)";

    public static final String BeforeRegex = "之前|前";

    public static final String AfterRegex = "之后|后";

    public static final String DateRegexList1 = "({LunarRegex}(\\s*))?((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?{MonthRegex}(\\s*){DateDayRegexInChinese}((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?"
            .replace("{LunarRegex}", LunarRegex)
            .replace("{YearRegex}", YearRegex)
            .replace("{DateYearInChineseRegex}", DateYearInChineseRegex)
            .replace("{MonthRegex}", MonthRegex)
            .replace("{DateDayRegexInChinese}", DateDayRegexInChinese)
            .replace("{WeekDayRegex}", WeekDayRegex)
            .replace("{BeforeRegex}", BeforeRegex)
            .replace("{AfterRegex}", AfterRegex);

    public static final String DateRegexList2 = "((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?({LunarRegex}(\\s*))?{MonthRegex}(\\s*){DateDayRegexInChinese}((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?"
            .replace("{MonthRegex}", MonthRegex)
            .replace("{DateDayRegexInChinese}", DateDayRegexInChinese)
            .replace("{YearRegex}", YearRegex)
            .replace("{LunarRegex}", LunarRegex)
            .replace("{WeekDayRegex}", WeekDayRegex)
            .replace("{DateYearInChineseRegex}", DateYearInChineseRegex)
            .replace("{BeforeRegex}", BeforeRegex)
            .replace("{AfterRegex}", AfterRegex);

    public static final String DateRegexList3 = "((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?({LunarRegex}(\\s*))?{MonthRegex}(\\s*)({DayRegexNumInChinese}|{DayRegex})((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?"
            .replace("{MonthRegex}", MonthRegex)
            .replace("{DayRegexNumInChinese}", DayRegexNumInChinese)
            .replace("{YearRegex}", YearRegex)
            .replace("{LunarRegex}", LunarRegex)
            .replace("{WeekDayRegex}", WeekDayRegex)
            .replace("{DateYearInChineseRegex}", DateYearInChineseRegex)
            .replace("{BeforeRegex}", BeforeRegex)
            .replace("{AfterRegex}", AfterRegex)
            .replace("{DayRegex}", DayRegex);

    public static final String DateRegexList4 = "{MonthNumRegex}\\s*/\\s*{DayRegex}((\\s+|\\s*,\\s*){YearRegex})?"
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{DayRegex}", DayRegex)
            .replace("{YearRegex}", YearRegex);

    public static final String DateRegexList5 = "{DayRegex}\\s*/\\s*{MonthNumRegex}((\\s+|\\s*,\\s*){YearRegex})?"
            .replace("{DayRegex}", DayRegex)
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{YearRegex}", YearRegex);

    public static final String DateRegexList6 = "{MonthNumRegex}\\s*[/\\\\\\-]\\s*{DayRegex}\\s*[/\\\\\\-]\\s*{YearRegex}"
            .replace("{DayRegex}", DayRegex)
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{YearRegex}", YearRegex);

    public static final String DateRegexList7 = "{DayRegex}\\s*[/\\\\\\-\\.]\\s*{MonthNumRegex}\\s*[/\\\\\\-\\.]\\s*{YearNumRegex}"
            .replace("{DayRegex}", DayRegex)
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{YearNumRegex}", YearNumRegex);

    public static final String DateRegexList8 = "{YearNumRegex}\\s*[/\\\\\\-\\. ]\\s*{MonthNumRegex}\\s*[/\\\\\\-\\. ]\\s*{DayRegex}"
            .replace("{YearNumRegex}", YearNumRegex)
            .replace("{MonthNumRegex}", MonthNumRegex)
            .replace("{DayRegex}", DayRegex);

    public static final String DatePeriodTillRegex = "(?<till>到|至|--|-|—|——|~|–)";

    public static final String DatePeriodDayRegexInChinese = "(?<day>初一|三十|一日|十一日|二十一日|三十一日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|一日|十一日|十日|二十一日|二十日|三十一日|三十日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|十日|二十日|三十日|10日|11日|12日|13日|14日|15日|16日|17日|18日|19日|1日|20日|21日|22日|23日|24日|25日|26日|27日|28日|29日|2日|30日|31日|3日|4日|5日|6日|7日|8日|9日|一号|十一号|二十一号|三十一号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|一号|十一号|十号|二十一号|二十号|三十一号|三十号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|十号|二十号|三十号|10号|11号|12号|13号|14号|15号|16号|17号|18号|19号|1号|20号|21号|22号|23号|24号|25号|26号|27号|28号|29号|2号|30号|31号|3号|4号|5号|6号|7号|8号|9号|一|十一|二十一|三十一|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|一|十一|十|二十一|二十|三十一|三十|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|十|二十|三十||廿|卅)";

    public static final String DatePeriodThisRegex = "这个|这一个|这|这一|本";

    public static final String DatePeriodLastRegex = "上个|上一个|上|上一";

    public static final String DatePeriodNextRegex = "下个|下一个|下|下一";

    public static final String RelativeMonthRegex = "(?<relmonth>({DatePeriodThisRegex}|{DatePeriodLastRegex}|{DatePeriodNextRegex})\\s*月)"
            .replace("{DatePeriodThisRegex}", DatePeriodThisRegex)
            .replace("{DatePeriodLastRegex}", DatePeriodLastRegex)
            .replace("{DatePeriodNextRegex}", DatePeriodNextRegex);

    public static final String DatePeriodYearRegex = "(({YearNumRegex})(\\s*年)?|({YearRegex})\\s*年)(?=[\\u4E00-\\u9FFF]|\\s|$|\\W)"
            .replace("{YearNumRegex}", YearNumRegex)
            .replace("{YearRegex}", YearRegex);

    public static final String StrictYearRegex = "{DatePeriodYearRegex}"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex);

    public static final String YearRegexInNumber = "(?<year>(\\d{3,4}))";

    public static final String DatePeriodYearInChineseRegex = "(?<yearchs>({ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}))年"
            .replace("{ZeroToNineIntegerRegexChs}", ZeroToNineIntegerRegexChs);

    public static final String MonthSuffixRegex = "(?<msuf>({RelativeMonthRegex}|{MonthRegex}))"
            .replace("{RelativeMonthRegex}", RelativeMonthRegex)
            .replace("{MonthRegex}", MonthRegex);

    public static final String SimpleCasesRegex = "((从)\\s*)?(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex})\\s*)?{MonthSuffixRegex}({DatePeriodDayRegexInChinese}|{DayRegex})\\s*{DatePeriodTillRegex}\\s*({DatePeriodDayRegexInChinese}|{DayRegex})((\\s+|\\s*,\\s*){DatePeriodYearRegex})?"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex)
            .replace("{MonthSuffixRegex}", MonthSuffixRegex)
            .replace("{DatePeriodDayRegexInChinese}", DatePeriodDayRegexInChinese)
            .replace("{DayRegex}", DayRegex)
            .replace("{DatePeriodTillRegex}", DatePeriodTillRegex);

    public static final String YearAndMonth = "({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex}){MonthRegex}"
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex)
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{MonthRegex}", MonthRegex);

    public static final String PureNumYearAndMonth = "({YearRegexInNumber}\\s*[-\\.\\/]\\s*{MonthNumRegex})|({MonthNumRegex}\\s*\\/\\s*{YearRegexInNumber})"
            .replace("{YearRegexInNumber}", YearRegexInNumber)
            .replace("{MonthNumRegex}", MonthNumRegex);

    public static final String OneWordPeriodRegex = "(((明年|今年|去年)\\s*)?{MonthRegex}|({DatePeriodThisRegex}|{DatePeriodLastRegex}|{DatePeriodNextRegex})\\s*(周末|周|月|年)|周末|今年|明年|去年|前年|后年)"
            .replace("{MonthRegex}", MonthRegex)
            .replace("{DatePeriodThisRegex}", DatePeriodThisRegex)
            .replace("{DatePeriodLastRegex}", DatePeriodLastRegex)
            .replace("{DatePeriodNextRegex}", DatePeriodNextRegex);

    public static final String WeekOfMonthRegex = "(?<wom>{MonthSuffixRegex}的(?<cardinal>第一|第二|第三|第四|第五|最后一)\\s*周\\s*)"
            .replace("{MonthSuffixRegex}", MonthSuffixRegex);

    public static final String UnitRegex = "(?<unit>年|(个)?月|周|日|天)";

    public static final String FollowedUnit = "^\\s*{UnitRegex}"
            .replace("{UnitRegex}", UnitRegex);

    public static final String NumberCombinedWithUnit = "(?<num>\\d+(\\.\\d*)?){UnitRegex}"
            .replace("{UnitRegex}", UnitRegex);

    public static final String YearToYear = "((从|在|自)\\s*)?({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})\\s*{DatePeriodTillRegex}\\s*({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})"
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex)
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodTillRegex}", DatePeriodTillRegex);

    public static final String MonthToMonth = "({MonthRegex}){DatePeriodTillRegex}({MonthRegex})"
            .replace("{MonthRegex}", MonthRegex)
            .replace("{DatePeriodTillRegex}", DatePeriodTillRegex);

    public static final String PastRegex = "(?<past>(前|上|之前|近))";

    public static final String FutureRegex = "(?<future>(后|(?<![一两几]\\s*)下|之后|未来(的)?))";

    public static final String SeasonRegex = "(?<season>春|夏|秋|冬)(天|季)?";

    public static final String SeasonWithYear = "(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?{SeasonRegex}"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex)
            .replace("{SeasonRegex}", SeasonRegex);

    public static final String QuarterRegex = "(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(第(?<cardinal>1|2|3|4|一|二|三|四)季度)"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex);

    public static final String CenturyRegex = "(?<century>\\d|1\\d|2\\d)世纪";

    public static final String CenturyRegexInChinese = "(?<century>一|二|三|四|五|六|七|八|九|十|十一|十二|十三|十四|十五|十六|十七|十八|十九|二十|二十一|二十二)世纪";

    public static final String RelativeCenturyRegex = "(?<relcentury>({DatePeriodLastRegex}|{DatePeriodThisRegex}|{DatePeriodNextRegex}))世纪"
            .replace("{DatePeriodLastRegex}", DatePeriodLastRegex)
            .replace("{DatePeriodThisRegex}", DatePeriodThisRegex)
            .replace("{DatePeriodNextRegex}", DatePeriodNextRegex);

    public static final String DecadeRegexInChinese = "(?<decade>十|一十|二十|三十|四十|五十|六十|七十|八十|九十)";

    public static final String DecadeRegex = "(?<centurysuf>({CenturyRegex}|{CenturyRegexInChinese}|{RelativeCenturyRegex}))?(?<decade>(\\d0|{DecadeRegexInChinese}))年代"
            .replace("{CenturyRegex}", CenturyRegex)
            .replace("{CenturyRegexInChinese}", CenturyRegexInChinese)
            .replace("{RelativeCenturyRegex}", RelativeCenturyRegex)
            .replace("{DecadeRegexInChinese}", DecadeRegexInChinese);

    public static final String PrepositionRegex = "(?<prep>^的|在$)";

    public static final String NowRegex = "(?<now>现在|马上|立刻|刚刚才|刚刚|刚才)";

    public static final String NightRegex = "(?<night>早|晚)";

    public static final String TimeOfTodayRegex = "(今晚|今早|今晨|明晚|明早|明晨|昨晚)(的|在)?";

    public static final String DateTimePeriodTillRegex = "(?<till>到|直到|--|-|—|——)";

    public static final String DateTimePeriodPrepositionRegex = "(?<prep>^\\s*的|在\\s*$)";

    public static final String HourRegex = "\\b{BaseDateTime.HourRegex}"
            .replace("{BaseDateTime.HourRegex}", BaseDateTime.HourRegex);

    public static final String HourNumRegex = "(?<hour>[零〇一二两三四五六七八九]|二十[一二三四]?|十[一二三四五六七八九]?)";

    public static final String ZhijianRegex = "^\\s*(之间|之内|期间|中间|间)";

    public static final String DateTimePeriodThisRegex = "这个|这一个|这|这一";

    public static final String DateTimePeriodLastRegex = "上个|上一个|上|上一";

    public static final String DateTimePeriodNextRegex = "下个|下一个|下|下一";

    public static final String DescRegex = "(?<desc>pm|am|p\\.m\\.|a\\.m\\.|p|a)";

    public static final String TimeOfDayRegex = "(?<timeOfDay>凌晨|清晨|早上|早|上午|中午|下午|午后|晚上|夜里|夜晚|半夜|夜间|深夜|傍晚|晚)";

    public static final String SpecificTimeOfDayRegex = "((({DateTimePeriodThisRegex}|{DateTimePeriodNextRegex}|{DateTimePeriodLastRegex})\\s+{TimeOfDayRegex})|(今晚|今早|今晨|明晚|明早|明晨|昨晚))"
            .replace("{DateTimePeriodThisRegex}", DateTimePeriodThisRegex)
            .replace("{DateTimePeriodNextRegex}", DateTimePeriodNextRegex)
            .replace("{DateTimePeriodLastRegex}", DateTimePeriodLastRegex)
            .replace("{TimeOfDayRegex}", TimeOfDayRegex);

    public static final String DateTimePeriodUnitRegex = "(个)?(?<unit>(小时|分钟|秒钟|时|分|秒))";

    public static final String DateTimePeriodFollowedUnit = "^\\s*{DateTimePeriodUnitRegex}"
            .replace("{DateTimePeriodUnitRegex}", DateTimePeriodUnitRegex);

    public static final String DateTimePeriodNumberCombinedWithUnit = "\\b(?<num>\\d+(\\.\\d*)?){DateTimePeriodUnitRegex}"
            .replace("{DateTimePeriodUnitRegex}", DateTimePeriodUnitRegex);

    public static final String DurationYearRegex = "((\\d{3,4})|0\\d|两千)\\s*年";

    public static final String DurationHalfSuffixRegex = "半";

    public static final Map<String, String> DurationSuffixList = ImmutableMap.<String, String>builder()
        .put("M", "分钟")
        .put("S", "秒钟|秒")
        .put("H", "个小时|小时")
        .put("D", "天")
        .put("W", "星期|个星期|周")
        .put("Mon", "个月")
        .put("Y", "年")
        .build();

    public static final List<String> DurationAmbiguousUnits = Arrays.asList("分钟", "秒钟", "秒", "个小时", "小时", "天", "星期", "个星期", "周", "个月", "年");

    public static final String LunarHolidayRegex = "(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>除夕|春节|中秋节|中秋|元宵节|端午节|端午|重阳节)"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex);

    public static final String HolidayRegexList1 = "(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>新年|五一|劳动节|元旦节|元旦|愚人节|圣诞节|植树节|国庆节|情人节|教师节|儿童节|妇女节|青年节|建军节|女生节|光棍节|双十一|清明节|清明)"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex);

    public static final String HolidayRegexList2 = "(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>母亲节|父亲节|感恩节|万圣节)"
            .replace("{DatePeriodYearRegex}", DatePeriodYearRegex)
            .replace("{DatePeriodYearInChineseRegex}", DatePeriodYearInChineseRegex);

    public static final String SetUnitRegex = "(?<unit>年|月|周|星期|日|天|小时|时|分钟|分|秒钟|秒)";

    public static final String SetEachUnitRegex = "(?<each>(每个|每一|每)\\s*{SetUnitRegex})"
            .replace("{SetUnitRegex}", SetUnitRegex);

    public static final String SetEachPrefixRegex = "(?<each>(每)\\s*$)";

    public static final String SetLastRegex = "(?<last>last|this|next)";

    public static final String SetEachDayRegex = "(每|每一)(天|日)\\s*$";

    public static final String TimeHourNumRegex = "(00|01|02|03|04|05|06|07|08|09|0|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|1|2|3|4|5|6|7|8|9)";

    public static final String TimeMinuteNumRegex = "(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)";

    public static final String TimeSecondNumRegex = "(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)";

    public static final String TimeHourChsRegex = "([零〇一二两三四五六七八九]|二十[一二三四]?|十[一二三四五六七八九]?)";

    public static final String TimeMinuteChsRegex = "([二三四五]?十[一二三四五六七八九]?|六十|[零〇一二三四五六七八九])";

    public static final String TimeSecondChsRegex = "{TimeMinuteChsRegex}"
            .replace("{TimeMinuteChsRegex}", TimeMinuteChsRegex);

    public static final String TimeClockDescRegex = "(点\\s*整|点\\s*钟|点|时)";

    public static final String TimeMinuteDescRegex = "(分钟|分|)";

    public static final String TimeSecondDescRegex = "(秒钟|秒)";

    public static final String TimeBanHourPrefixRegex = "(第)";

    public static final String TimeHourRegex = "(?<!{TimeBanHourPrefixRegex})(?<hour>{TimeHourChsRegex}|{TimeHourNumRegex}){TimeClockDescRegex}"
            .replace("{TimeBanHourPrefixRegex}", TimeBanHourPrefixRegex)
            .replace("{TimeHourChsRegex}", TimeHourChsRegex)
            .replace("{TimeHourNumRegex}", TimeHourNumRegex)
            .replace("{TimeClockDescRegex}", TimeClockDescRegex);

    public static final String TimeMinuteRegex = "(?<min>{TimeMinuteChsRegex}|{TimeMinuteNumRegex}){TimeMinuteDescRegex}"
            .replace("{TimeMinuteChsRegex}", TimeMinuteChsRegex)
            .replace("{TimeMinuteNumRegex}", TimeMinuteNumRegex)
            .replace("{TimeMinuteDescRegex}", TimeMinuteDescRegex);

    public static final String TimeSecondRegex = "(?<sec>{TimeSecondChsRegex}|{TimeSecondNumRegex}){TimeSecondDescRegex}"
            .replace("{TimeSecondChsRegex}", TimeSecondChsRegex)
            .replace("{TimeSecondNumRegex}", TimeSecondNumRegex)
            .replace("{TimeSecondDescRegex}", TimeSecondDescRegex);

    public static final String TimeHalfRegex = "(?<half>过半|半)";

    public static final String TimeQuarterRegex = "(?<quarter>[一两二三四1-4])\\s*(刻钟|刻)";

    public static final String TimeChineseTimeRegex = "{TimeHourRegex}({TimeQuarterRegex}|{TimeHalfRegex}|((过|又)?{TimeMinuteRegex})({TimeSecondRegex})?)?"
            .replace("{TimeHourRegex}", TimeHourRegex)
            .replace("{TimeQuarterRegex}", TimeQuarterRegex)
            .replace("{TimeHalfRegex}", TimeHalfRegex)
            .replace("{TimeMinuteRegex}", TimeMinuteRegex)
            .replace("{TimeSecondRegex}", TimeSecondRegex);

    public static final String TimeDigitTimeRegex = "(?<hour>{TimeHourNumRegex}):(?<min>{TimeMinuteNumRegex})(:(?<sec>{TimeSecondNumRegex}))?"
            .replace("{TimeHourNumRegex}", TimeHourNumRegex)
            .replace("{TimeMinuteNumRegex}", TimeMinuteNumRegex)
            .replace("{TimeSecondNumRegex}", TimeSecondNumRegex);

    public static final String TimeDayDescRegex = "(?<daydesc>凌晨|清晨|早上|早|上午|中午|下午|午后|晚上|夜里|夜晚|半夜|午夜|夜间|深夜|傍晚|晚)";

    public static final String TimeApproximateDescPreffixRegex = "(大[约概]|差不多|可能|也许|约|不超过|不多[于过]|最[多长少]|少于|[超短长多]过|几乎要|将近|差点|快要|接近|至少|起码|超出|不到)";

    public static final String TimeApproximateDescSuffixRegex = "(之前|以前|以后|之后|前|后|左右)";

    public static final String TimeRegexes1 = "{TimeApproximateDescPreffixRegex}?{TimeDayDescRegex}?{TimeChineseTimeRegex}{TimeApproximateDescSuffixRegex}?"
            .replace("{TimeApproximateDescPreffixRegex}", TimeApproximateDescPreffixRegex)
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeChineseTimeRegex}", TimeChineseTimeRegex)
            .replace("{TimeApproximateDescSuffixRegex}", TimeApproximateDescSuffixRegex);

    public static final String TimeRegexes2 = "{TimeApproximateDescPreffixRegex}?{TimeDayDescRegex}?{TimeDigitTimeRegex}{TimeApproximateDescSuffixRegex}?"
            .replace("{TimeApproximateDescPreffixRegex}", TimeApproximateDescPreffixRegex)
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeDigitTimeRegex}", TimeDigitTimeRegex)
            .replace("{TimeApproximateDescSuffixRegex}", TimeApproximateDescSuffixRegex);

    public static final String TimeRegexes3 = "差{TimeMinuteRegex}{TimeChineseTimeRegex}"
            .replace("{TimeMinuteRegex}", TimeMinuteRegex)
            .replace("{TimeChineseTimeRegex}", TimeChineseTimeRegex);

    public static final String TimePeriodTimePeriodConnectWords = "(起|至|到|–|-|—|~|～)";

    public static final String TimePeriodLeftChsTimeRegex = "(从)?(?<left>{TimeDayDescRegex}?({TimeChineseTimeRegex}))"
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeChineseTimeRegex}", TimeChineseTimeRegex);

    public static final String TimePeriodRightChsTimeRegex = "{TimePeriodTimePeriodConnectWords}(?<right>{TimeDayDescRegex}?{TimeChineseTimeRegex})(之间)?"
            .replace("{TimePeriodTimePeriodConnectWords}", TimePeriodTimePeriodConnectWords)
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeChineseTimeRegex}", TimeChineseTimeRegex);

    public static final String TimePeriodLeftDigitTimeRegex = "(从)?(?<left>{TimeDayDescRegex}?({TimeDigitTimeRegex}))"
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeDigitTimeRegex}", TimeDigitTimeRegex);

    public static final String TimePeriodRightDigitTimeRegex = "{TimePeriodTimePeriodConnectWords}(?<right>{TimeDayDescRegex}?{TimeDigitTimeRegex})(之间)?"
            .replace("{TimePeriodTimePeriodConnectWords}", TimePeriodTimePeriodConnectWords)
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeDigitTimeRegex}", TimeDigitTimeRegex);

    public static final String TimePeriodShortLeftChsTimeRegex = "(从)?(?<left>{TimeDayDescRegex}?({TimeHourChsRegex}))"
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeHourChsRegex}", TimeHourChsRegex);

    public static final String TimePeriodShortLeftDigitTimeRegex = "(从)?(?<left>{TimeDayDescRegex}?({TimeHourNumRegex}))"
            .replace("{TimeDayDescRegex}", TimeDayDescRegex)
            .replace("{TimeHourNumRegex}", TimeHourNumRegex);

    public static final String TimePeriodRegexes1 = "({TimePeriodLeftDigitTimeRegex}{TimePeriodRightDigitTimeRegex}|{TimePeriodLeftChsTimeRegex}{TimePeriodRightChsTimeRegex})"
            .replace("{TimePeriodLeftDigitTimeRegex}", TimePeriodLeftDigitTimeRegex)
            .replace("{TimePeriodRightDigitTimeRegex}", TimePeriodRightDigitTimeRegex)
            .replace("{TimePeriodLeftChsTimeRegex}", TimePeriodLeftChsTimeRegex)
            .replace("{TimePeriodRightChsTimeRegex}", TimePeriodRightChsTimeRegex);

    public static final String TimePeriodRegexes2 = "({TimePeriodShortLeftDigitTimeRegex}{TimePeriodRightDigitTimeRegex}|{TimePeriodShortLeftChsTimeRegex}{TimePeriodRightChsTimeRegex})"
            .replace("{TimePeriodShortLeftDigitTimeRegex}", TimePeriodShortLeftDigitTimeRegex)
            .replace("{TimePeriodRightDigitTimeRegex}", TimePeriodRightDigitTimeRegex)
            .replace("{TimePeriodShortLeftChsTimeRegex}", TimePeriodShortLeftChsTimeRegex)
            .replace("{TimePeriodRightChsTimeRegex}", TimePeriodRightChsTimeRegex);

    public static final String ParserConfigurationBefore = "(之前|以前|前)";

    public static final String ParserConfigurationAfter = "(之后|以后|后)";

    public static final String ParserConfigurationUntil = "(直到|直至|截至|截止(到)?)";

    public static final String ParserConfigurationSincePrefix = "(自从|自|自打|打)";

    public static final String ParserConfigurationSinceSuffix = "(以来|开始)";

    public static final String ParserConfigurationLastWeekDayToken = "最后一个";

    public static final String ParserConfigurationNextMonthToken = "下一个";

    public static final String ParserConfigurationLastMonthToken = "上一个";

    public static final String ParserConfigurationDatePrefix = " ";

    public static final Map<String, String> ParserConfigurationUnitMap = ImmutableMap.<String, String>builder()
        .put("年", "Y")
        .put("月", "MON")
        .put("个月", "MON")
        .put("日", "D")
        .put("周", "W")
        .put("天", "D")
        .put("小时", "H")
        .put("时", "H")
        .put("分钟", "M")
        .put("分", "M")
        .put("秒钟", "S")
        .put("秒", "S")
        .put("星期", "W")
        .build();

    public static final Map<String, Long> ParserConfigurationUnitValueMap = ImmutableMap.<String, Long>builder()
        .put("years", 31536000L)
        .put("year", 31536000L)
        .put("months", 2592000L)
        .put("month", 2592000L)
        .put("weeks", 604800L)
        .put("week", 604800L)
        .put("days", 86400L)
        .put("day", 86400L)
        .put("hours", 3600L)
        .put("hour", 3600L)
        .put("hrs", 3600L)
        .put("hr", 3600L)
        .put("h", 3600L)
        .put("minutes", 60L)
        .put("minute", 60L)
        .put("mins", 60L)
        .put("min", 60L)
        .put("seconds", 1L)
        .put("second", 1L)
        .put("secs", 1L)
        .put("sec", 1L)
        .build();

    public static final Map<String, String> ParserConfigurationSeasonMap = ImmutableMap.<String, String>builder()
        .put("春", "SP")
        .put("夏", "SU")
        .put("秋", "FA")
        .put("冬", "WI")
        .build();

    public static final Map<String, Long> ParserConfigurationSeasonValueMap = ImmutableMap.<String, Long>builder()
        .put("SP", 3L)
        .put("SU", 6L)
        .put("FA", 9L)
        .put("WI", 12L)
        .build();

    public static final Map<String, Long> ParserConfigurationCardinalMap = ImmutableMap.<String, Long>builder()
        .put("一", 1L)
        .put("二", 2L)
        .put("三", 3L)
        .put("四", 4L)
        .put("五", 5L)
        .put("1", 1L)
        .put("2", 2L)
        .put("3", 3L)
        .put("4", 4L)
        .put("5", 5L)
        .put("第一个", 1L)
        .put("第二个", 2L)
        .put("第三个", 3L)
        .put("第四个", 4L)
        .put("第五个", 5L)
        .put("第一", 1L)
        .put("第二", 2L)
        .put("第三", 3L)
        .put("第四", 4L)
        .put("第五", 5L)
        .build();

    public static final Map<String, Long> ParserConfigurationDayOfMonth = ImmutableMap.<String, Long>builder()
        .put("01", 1L)
        .put("02", 2L)
        .put("03", 3L)
        .put("04", 4L)
        .put("05", 5L)
        .put("06", 6L)
        .put("07", 7L)
        .put("08", 8L)
        .put("09", 9L)
        .put("1", 1L)
        .put("2", 2L)
        .put("3", 3L)
        .put("4", 4L)
        .put("5", 5L)
        .put("6", 6L)
        .put("7", 7L)
        .put("8", 8L)
        .put("9", 9L)
        .put("10", 10L)
        .put("11", 11L)
        .put("12", 12L)
        .put("13", 13L)
        .put("14", 14L)
        .put("15", 15L)
        .put("16", 16L)
        .put("17", 17L)
        .put("18", 18L)
        .put("19", 19L)
        .put("20", 20L)
        .put("21", 21L)
        .put("22", 22L)
        .put("23", 23L)
        .put("24", 24L)
        .put("25", 25L)
        .put("26", 26L)
        .put("27", 27L)
        .put("28", 28L)
        .put("29", 29L)
        .put("30", 30L)
        .put("31", 31L)
        .put("1日", 1L)
        .put("2日", 2L)
        .put("3日", 3L)
        .put("4日", 4L)
        .put("5日", 5L)
        .put("6日", 6L)
        .put("7日", 7L)
        .put("8日", 8L)
        .put("9日", 9L)
        .put("10日", 10L)
        .put("11日", 11L)
        .put("12日", 12L)
        .put("13日", 13L)
        .put("14日", 14L)
        .put("15日", 15L)
        .put("16日", 16L)
        .put("17日", 17L)
        .put("18日", 18L)
        .put("19日", 19L)
        .put("20日", 20L)
        .put("21日", 21L)
        .put("22日", 22L)
        .put("23日", 23L)
        .put("24日", 24L)
        .put("25日", 25L)
        .put("26日", 26L)
        .put("27日", 27L)
        .put("28日", 28L)
        .put("29日", 29L)
        .put("30日", 30L)
        .put("31日", 31L)
        .put("一日", 1L)
        .put("十一日", 11L)
        .put("二十日", 20L)
        .put("十日", 10L)
        .put("二十一日", 21L)
        .put("三十一日", 31L)
        .put("二日", 2L)
        .put("三日", 3L)
        .put("四日", 4L)
        .put("五日", 5L)
        .put("六日", 6L)
        .put("七日", 7L)
        .put("八日", 8L)
        .put("九日", 9L)
        .put("十二日", 12L)
        .put("十三日", 13L)
        .put("十四日", 14L)
        .put("十五日", 15L)
        .put("十六日", 16L)
        .put("十七日", 17L)
        .put("十八日", 18L)
        .put("十九日", 19L)
        .put("二十二日", 22L)
        .put("二十三日", 23L)
        .put("二十四日", 24L)
        .put("二十五日", 25L)
        .put("二十六日", 26L)
        .put("二十七日", 27L)
        .put("二十八日", 28L)
        .put("二十九日", 29L)
        .put("三十日", 30L)
        .put("1号", 1L)
        .put("2号", 2L)
        .put("3号", 3L)
        .put("4号", 4L)
        .put("5号", 5L)
        .put("6号", 6L)
        .put("7号", 7L)
        .put("8号", 8L)
        .put("9号", 9L)
        .put("10号", 10L)
        .put("11号", 11L)
        .put("12号", 12L)
        .put("13号", 13L)
        .put("14号", 14L)
        .put("15号", 15L)
        .put("16号", 16L)
        .put("17号", 17L)
        .put("18号", 18L)
        .put("19号", 19L)
        .put("20号", 20L)
        .put("21号", 21L)
        .put("22号", 22L)
        .put("23号", 23L)
        .put("24号", 24L)
        .put("25号", 25L)
        .put("26号", 26L)
        .put("27号", 27L)
        .put("28号", 28L)
        .put("29号", 29L)
        .put("30号", 30L)
        .put("31号", 31L)
        .put("一号", 1L)
        .put("十一号", 11L)
        .put("二十号", 20L)
        .put("十号", 10L)
        .put("二十一号", 21L)
        .put("三十一号", 31L)
        .put("二号", 2L)
        .put("三号", 3L)
        .put("四号", 4L)
        .put("五号", 5L)
        .put("六号", 6L)
        .put("七号", 7L)
        .put("八号", 8L)
        .put("九号", 9L)
        .put("十二号", 12L)
        .put("十三号", 13L)
        .put("十四号", 14L)
        .put("十五号", 15L)
        .put("十六号", 16L)
        .put("十七号", 17L)
        .put("十八号", 18L)
        .put("十九号", 19L)
        .put("二十二号", 22L)
        .put("二十三号", 23L)
        .put("二十四号", 24L)
        .put("二十五号", 25L)
        .put("二十六号", 26L)
        .put("二十七号", 27L)
        .put("二十八号", 28L)
        .put("二十九号", 29L)
        .put("三十号", 30L)
        .put("初一", 32L)
        .put("三十", 30L)
        .put("一", 1L)
        .put("十一", 11L)
        .put("二十", 20L)
        .put("十", 10L)
        .put("二十一", 21L)
        .put("三十一", 31L)
        .put("二", 2L)
        .put("三", 3L)
        .put("四", 4L)
        .put("五", 5L)
        .put("六", 6L)
        .put("七", 7L)
        .put("八", 8L)
        .put("九", 9L)
        .put("十二", 12L)
        .put("十三", 13L)
        .put("十四", 14L)
        .put("十五", 15L)
        .put("十六", 16L)
        .put("十七", 17L)
        .put("十八", 18L)
        .put("十九", 19L)
        .put("二十二", 22L)
        .put("二十三", 23L)
        .put("二十四", 24L)
        .put("二十五", 25L)
        .put("二十六", 26L)
        .put("二十七", 27L)
        .put("二十八", 28L)
        .put("二十九", 29L)
        .build();

    public static final Map<String, Long> ParserConfigurationDayOfWeek = ImmutableMap.<String, Long>builder()
        .put("星期一", 1L)
        .put("星期二", 2L)
        .put("星期三", 3L)
        .put("星期四", 4L)
        .put("星期五", 5L)
        .put("星期六", 6L)
        .put("星期天", 0L)
        .put("星期日", 0L)
        .put("礼拜一", 1L)
        .put("礼拜二", 2L)
        .put("礼拜三", 3L)
        .put("礼拜四", 4L)
        .put("礼拜五", 5L)
        .put("礼拜六", 6L)
        .put("礼拜天", 0L)
        .put("礼拜日", 0L)
        .put("周一", 1L)
        .put("周二", 2L)
        .put("周三", 3L)
        .put("周四", 4L)
        .put("周五", 5L)
        .put("周六", 6L)
        .put("周日", 0L)
        .put("周天", 0L)
        .build();

    public static final Map<String, Long> ParserConfigurationMonthOfYear = ImmutableMap.<String, Long>builder()
        .put("1", 1L)
        .put("2", 2L)
        .put("3", 3L)
        .put("4", 4L)
        .put("5", 5L)
        .put("6", 6L)
        .put("7", 7L)
        .put("8", 8L)
        .put("9", 9L)
        .put("10", 10L)
        .put("11", 11L)
        .put("12", 12L)
        .put("01", 1L)
        .put("02", 2L)
        .put("03", 3L)
        .put("04", 4L)
        .put("05", 5L)
        .put("06", 6L)
        .put("07", 7L)
        .put("08", 8L)
        .put("09", 9L)
        .put("一月", 1L)
        .put("二月", 2L)
        .put("三月", 3L)
        .put("四月", 4L)
        .put("五月", 5L)
        .put("六月", 6L)
        .put("七月", 7L)
        .put("八月", 8L)
        .put("九月", 9L)
        .put("十月", 10L)
        .put("十一月", 11L)
        .put("十二月", 12L)
        .put("1月", 1L)
        .put("2月", 2L)
        .put("3月", 3L)
        .put("4月", 4L)
        .put("5月", 5L)
        .put("6月", 6L)
        .put("7月", 7L)
        .put("8月", 8L)
        .put("9月", 9L)
        .put("10月", 10L)
        .put("11月", 11L)
        .put("12月", 12L)
        .put("01月", 1L)
        .put("02月", 2L)
        .put("03月", 3L)
        .put("04月", 4L)
        .put("05月", 5L)
        .put("06月", 6L)
        .put("07月", 7L)
        .put("08月", 8L)
        .put("09月", 9L)
        .put("正月", 13L)
        .put("大年", 13L)
        .build();

    public static final String DateTimeSimpleAmRegex = "(?<am>早|晨)";

    public static final String DateTimeSimplePmRegex = "(?<pm>晚)";

    public static final String DateTimePeriodMORegex = "(凌晨|清晨|早上|早|上午)";

    public static final String DateTimePeriodAFRegex = "(中午|下午|午后|傍晚)";

    public static final String DateTimePeriodEVRegex = "(晚上|夜里|夜晚|晚)";

    public static final String DateTimePeriodNIRegex = "(半夜|夜间|深夜)";

    public static final Map<String, Long> DurationUnitValueMap = ImmutableMap.<String, Long>builder()
        .put("Y", 31536000L)
        .put("Mon", 2592000L)
        .put("W", 604800L)
        .put("D", 86400L)
        .put("H", 3600L)
        .put("M", 60L)
        .put("S", 1L)
        .build();

    public static final Map<String, String> HolidayNoFixedTimex = ImmutableMap.<String, String>builder()
        .put("父亲节", "-06-WXX-6-3")
        .put("母亲节", "-05-WXX-7-2")
        .put("感恩节", "-11-WXX-4-4")
        .build();

    public static final String MergedBeforeRegex = "(前|之前)$";

    public static final String MergedAfterRegex = "(后|之后)$";

    public static final Map<Character, Long> TimeNumberDictionary = ImmutableMap.<Character, Long>builder()
        .put('零', 0L)
        .put('一', 1L)
        .put('二', 2L)
        .put('三', 3L)
        .put('四', 4L)
        .put('五', 5L)
        .put('六', 6L)
        .put('七', 7L)
        .put('八', 8L)
        .put('九', 9L)
        .put('〇', 0L)
        .put('两', 2L)
        .put('十', 10L)
        .build();

    public static final Map<String, Long> TimeLowBoundDesc = ImmutableMap.<String, Long>builder()
        .put("中午", 11L)
        .put("下午", 12L)
        .put("午后", 12L)
        .put("晚上", 18L)
        .put("夜里", 18L)
        .put("夜晚", 18L)
        .put("夜间", 18L)
        .put("深夜", 18L)
        .put("傍晚", 18L)
        .put("晚", 18L)
        .build();

    public static final String DefaultLanguageFallback = "DMY";
}
