# ------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
# ------------------------------------------------------------------------------

from .base_date_time import BaseDateTime
# pylint: disable=line-too-long
class ChineseDateTime:
    MonthRegex = f'(?<month>正月|一月|二月|三月|四月|五月|六月|七月|八月|九月|十月|十一月|十二月|01月|02月|03月|04月|05月|06月|07月|08月|09月|10月|11月|12月|1月|2月|3月|4月|5月|6月|7月|8月|9月|大年)'
    DayRegex = f'(?<day>01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|1|2|3|4|5|6|7|8|9)'
    DateDayRegexInChinese = f'(?<day>初一|三十|一日|十一日|二十一日|三十一日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|一日|十一日|十日|二十一日|二十日|三十一日|三十日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|十日|二十日|三十日|10日|11日|12日|13日|14日|15日|16日|17日|18日|19日|1日|20日|21日|22日|23日|24日|25日|26日|27日|28日|29日|2日|30日|31日|3日|4日|5日|6日|7日|8日|9日|一号|十一号|二十一号|三十一号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|一号|十一号|十号|二十一号|二十号|三十一号|三十号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|十号|二十号|三十号|10号|11号|12号|13号|14号|15号|16号|17号|18号|19号|1号|20号|21号|22号|23号|24号|25号|26号|27号|28号|29号|2号|30号|31号|3号|4号|5号|6号|7号|8号|9号)'
    DayRegexNumInChinese = f'(?<day>一|十一|二十一|三十一|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|一|十一|十|二十一|二十|三十一|三十|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|十|二十|廿|卅)'
    MonthNumRegex = f'(?<month>01|02|03|04|05|06|07|08|09|10|11|12|1|2|3|4|5|6|7|8|9)'
    TwoNumYear = '50'
    YearNumRegex = f'(?<year>((1[5-9]|20)\\d{{2}})|2100)'
    YearRegex = f'(?<year>(\\d{{2,4}}))'
    ZeroToNineIntegerRegexChs = f'[一二三四五六七八九零壹贰叁肆伍陆柒捌玖〇两千俩倆仨]'
    DateYearInChineseRegex = f'(?<yearchs>({ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}))'
    WeekDayRegex = f'(?<weekday>周日|周天|周一|周二|周三|周四|周五|周六|星期一|星期二|星期三|星期四|星期五|星期六|星期日|星期天|礼拜一|礼拜二|礼拜三|礼拜四|礼拜五|礼拜六|礼拜日|礼拜天|禮拜一|禮拜二|禮拜三|禮拜四|禮拜五|禮拜六|禮拜日|禮拜天|週日|週天|週一|週二|週三|週四|週五|週六)'
    LunarRegex = f'(农历|初一|正月|大年)'
    DateThisRegex = f'(这个|这一个|这|这一|本){WeekDayRegex}'
    DateLastRegex = f'(上一个|上个|上一|上|最后一个|最后)(的)?{WeekDayRegex}'
    DateNextRegex = f'(下一个|下个|下一|下)(的)?{WeekDayRegex}'
    SpecialDayRegex = f'(最近|前天|后天|昨天|明天|今天|今日|明日|昨日|大后天|大前天|後天|大後天)'
    SpecialDayWithNumRegex = f'^[.]'
    WeekDayOfMonthRegex = f'((({MonthRegex}|{MonthNumRegex})的\\s*)(?<cardinal>第一个|第二个|第三个|第四个|第五个|最后一个)\\s*{WeekDayRegex})'
    DateThisRe = f'这个|这一个|这|这一|本|今'
    DateLastRe = f'上个|上一个|上|上一|去'
    DateNextRe = f'下个|下一个|下|下一|明'
    SpecialDate = f'(?<thisyear>({DateThisRe}|{DateLastRe}|{DateNextRe})年)?(?<thismonth>({DateThisRe}|{DateLastRe}|{DateNextRe})月)?{DateDayRegexInChinese}'
    DateUnitRegex = f'(?<unit>年|个月|周|日|天)'
    BeforeRegex = f'以前|之前|前'
    AfterRegex = f'以后|以後|之后|之後|后|後'
    DateRegexList1 = f'({LunarRegex}(\\s*))?((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?{MonthRegex}(\\s*){DateDayRegexInChinese}((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?'
    DateRegexList2 = f'((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?({LunarRegex}(\\s*))?{MonthRegex}(\\s*){DateDayRegexInChinese}((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?'
    DateRegexList3 = f'((({YearRegex}|{DateYearInChineseRegex})年)(\\s*))?({LunarRegex}(\\s*))?{MonthRegex}(\\s*)({DayRegexNumInChinese}|{DayRegex})((\\s*|,|，){WeekDayRegex})?({BeforeRegex}|{AfterRegex})?'
    DateRegexList4 = f'{MonthNumRegex}\\s*/\\s*{DayRegex}((\\s+|\\s*,\\s*){YearRegex})?'
    DateRegexList5 = f'{DayRegex}\\s*/\\s*{MonthNumRegex}((\\s+|\\s*,\\s*){YearRegex})?'
    DateRegexList6 = f'{MonthNumRegex}\\s*[/\\\\\\-]\\s*{DayRegex}\\s*[/\\\\\\-]\\s*{YearRegex}'
    DateRegexList7 = f'{DayRegex}\\s*[/\\\\\\-\\.]\\s*{MonthNumRegex}\\s*[/\\\\\\-\\.]\\s*{YearNumRegex}'
    DateRegexList8 = f'{YearNumRegex}\\s*[/\\\\\\-\\. ]\\s*{MonthNumRegex}\\s*[/\\\\\\-\\. ]\\s*{DayRegex}'
    DatePeriodTillRegex = f'(?<till>到|至|--|-|—|——|~|–)'
    DatePeriodTillSuffixRequiredRegex = f'(?<till>与|和)'
    DatePeriodDayRegexInChinese = f'(?<day>初一|三十|一日|十一日|二十一日|三十一日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|一日|十一日|十日|二十一日|二十日|三十一日|三十日|二日|三日|四日|五日|六日|七日|八日|九日|十二日|十三日|十四日|十五日|十六日|十七日|十八日|十九日|二十二日|二十三日|二十四日|二十五日|二十六日|二十七日|二十八日|二十九日|十日|二十日|三十日|10日|11日|12日|13日|14日|15日|16日|17日|18日|19日|1日|20日|21日|22日|23日|24日|25日|26日|27日|28日|29日|2日|30日|31日|3日|4日|5日|6日|7日|8日|9日|一号|十一号|二十一号|三十一号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|一号|十一号|十号|二十一号|二十号|三十一号|三十号|二号|三号|四号|五号|六号|七号|八号|九号|十二号|十三号|十四号|十五号|十六号|十七号|十八号|十九号|二十二号|二十三号|二十四号|二十五号|二十六号|二十七号|二十八号|二十九号|十号|二十号|三十号|10号|11号|12号|13号|14号|15号|16号|17号|18号|19号|1号|20号|21号|22号|23号|24号|25号|26号|27号|28号|29号|2号|30号|31号|3号|4号|5号|6号|7号|8号|9号|一|十一|二十一|三十一|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|一|十一|十|二十一|二十|三十一|三十|二|三|四|五|六|七|八|九|十二|十三|十四|十五|十六|十七|十八|十九|二十二|二十三|二十四|二十五|二十六|二十七|二十八|二十九|十|二十|三十||廿|卅)'
    DatePeriodThisRegex = f'这个|这一个|这|这一|本'
    DatePeriodLastRegex = f'上个|上一个|上|上一'
    DatePeriodNextRegex = f'下个|下一个|下|下一'
    RelativeMonthRegex = f'(?<relmonth>({DatePeriodThisRegex}|{DatePeriodLastRegex}|{DatePeriodNextRegex})\\s*月)'
    DatePeriodYearRegex = f'(({YearNumRegex})(\\s*年)?|({YearRegex})\\s*年)(?=[\\u4E00-\\u9FFF]|\\s|$|\\W)'
    StrictYearRegex = f'{DatePeriodYearRegex}'
    YearRegexInNumber = f'(?<year>(\\d{{3,4}}))'
    DatePeriodYearInChineseRegex = f'(?<yearchs>({ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}|{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}{ZeroToNineIntegerRegexChs}))年'
    MonthSuffixRegex = f'(?<msuf>({RelativeMonthRegex}|{MonthRegex}))'
    SimpleCasesRegex = f'((从)\\s*)?(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex})\\s*)?{MonthSuffixRegex}({DatePeriodDayRegexInChinese}|{DayRegex})\\s*{DatePeriodTillRegex}\\s*({DatePeriodDayRegexInChinese}|{DayRegex})((\\s+|\\s*,\\s*){DatePeriodYearRegex})?'
    YearAndMonth = f'({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex}){MonthRegex}'
    PureNumYearAndMonth = f'({YearRegexInNumber}\\s*[-\\.\\/]\\s*{MonthNumRegex})|({MonthNumRegex}\\s*\\/\\s*{YearRegexInNumber})'
    OneWordPeriodRegex = f'(((明年|今年|去年)\\s*)?{MonthRegex}|({DatePeriodThisRegex}|{DatePeriodLastRegex}|{DatePeriodNextRegex})\\s*(周末|周|月|年)|周末|今年|明年|去年|前年|后年)'
    WeekOfMonthRegex = f'(?<wom>{MonthSuffixRegex}的(?<cardinal>第一|第二|第三|第四|第五|最后一)\\s*周\\s*)'
    UnitRegex = f'(?<unit>年|(个)?月|周|日|天)'
    FollowedUnit = f'^\\s*{UnitRegex}'
    NumberCombinedWithUnit = f'(?<num>\\d+(\\.\\d*)?){UnitRegex}'
    DateRangePrepositions = f'((从|在|自)\\s*)?'
    YearToYear = f'({DateRangePrepositions})({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})\\s*({DatePeriodTillRegex}|后|後|之后|之後)\\s*({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})(\\s*((之间|之内|期间|中间|间)|前|之前))?'
    YearToYearSuffixRequired = f'({DateRangePrepositions})({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})\\s*({DatePeriodTillSuffixRequiredRegex})\\s*({DatePeriodYearInChineseRegex}|{DatePeriodYearRegex})\\s*(之间|之内|期间|中间|间)'
    MonthToMonth = f'({DateRangePrepositions})({MonthRegex}){DatePeriodTillRegex}({MonthRegex})'
    MonthToMonthSuffixRequired = f'({DateRangePrepositions})({MonthRegex}){DatePeriodTillSuffixRequiredRegex}({MonthRegex})\\s*(之间|之内|期间|中间|间)'
    PastRegex = f'(?<past>(之前|前|上|近|过去))'
    FutureRegex = f'(?<future>(之后|之後|后|後|(?<![一两几]\\s*)下|未来(的)?))'
    SeasonRegex = f'(?<season>春|夏|秋|冬)(天|季)?'
    SeasonWithYear = f'(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?{SeasonRegex}'
    QuarterRegex = f'(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(第(?<cardinal>1|2|3|4|一|二|三|四)季度)'
    CenturyRegex = f'(?<century>\\d|1\\d|2\\d)世纪'
    CenturyRegexInChinese = f'(?<century>一|二|三|四|五|六|七|八|九|十|十一|十二|十三|十四|十五|十六|十七|十八|十九|二十|二十一|二十二)世纪'
    RelativeCenturyRegex = f'(?<relcentury>({DatePeriodLastRegex}|{DatePeriodThisRegex}|{DatePeriodNextRegex}))世纪'
    DecadeRegexInChinese = f'(?<decade>十|一十|二十|三十|四十|五十|六十|七十|八十|九十)'
    DecadeRegex = f'(?<centurysuf>({CenturyRegex}|{CenturyRegexInChinese}|{RelativeCenturyRegex}))?(?<decade>(\\d0|{DecadeRegexInChinese}))年代'
    PrepositionRegex = f'(?<prep>^的|在$)'
    NowRegex = f'(?<now>现在|马上|立刻|刚刚才|刚刚|刚才)'
    NightRegex = f'(?<night>早|晚)'
    TimeOfTodayRegex = f'(今晚|今早|今晨|明晚|明早|明晨|昨晚)(的|在)?'
    DateTimePeriodTillRegex = f'(?<till>到|直到|--|-|—|——)'
    DateTimePeriodPrepositionRegex = f'(?<prep>^\\s*的|在\\s*$)'
    HourRegex = f'\\b{BaseDateTime.HourRegex}'
    HourNumRegex = f'(?<hour>[零〇一二两三四五六七八九]|二十[一二三四]?|十[一二三四五六七八九]?)'
    ZhijianRegex = f'^\\s*(之间|之内|期间|中间|间)'
    DateTimePeriodThisRegex = f'这个|这一个|这|这一'
    DateTimePeriodLastRegex = f'上个|上一个|上|上一'
    DateTimePeriodNextRegex = f'下个|下一个|下|下一'
    AmPmDescRegex = f'(?<daydesc>(am|a\\.m\\.|a m|a\\. m\\.|a\\.m|a\\. m|a m|pm|p\\.m\\.|p m|p\\. m\\.|p\\.m|p\\. m|p m))'
    TimeOfDayRegex = f'(?<timeOfDay>凌晨|清晨|早上|早|上午|中午|下午|午后|晚上|夜里|夜晚|半夜|夜间|深夜|傍晚|晚)'
    SpecificTimeOfDayRegex = f'((({DateTimePeriodThisRegex}|{DateTimePeriodNextRegex}|{DateTimePeriodLastRegex})\\s+{TimeOfDayRegex})|(今晚|今早|今晨|明晚|明早|明晨|昨晚))'
    DateTimePeriodUnitRegex = f'(个)?(?<unit>(小时|分钟|秒钟|时|分|秒))'
    DateTimePeriodFollowedUnit = f'^\\s*{DateTimePeriodUnitRegex}'
    DateTimePeriodNumberCombinedWithUnit = f'\\b(?<num>\\d+(\\.\\d*)?){DateTimePeriodUnitRegex}'
    DurationYearRegex = f'((\\d{{3,4}})|0\\d|两千)\\s*年'
    DurationHalfSuffixRegex = f'半'
    DurationSuffixList = dict([(r'''M''', r'''分钟'''),
                               (r'''S''', r'''秒钟|秒'''),
                               (r'''H''', r'''个小时|小时'''),
                               (r'''D''', r'''天'''),
                               (r'''W''', r'''星期|个星期|周'''),
                               (r'''Mon''', r'''个月'''),
                               (r'''Y''', r'''年''')])
    DurationAmbiguousUnits = [r'分钟', r'秒钟', r'秒', r'个小时', r'小时', r'天', r'星期', r'个星期', r'周', r'个月', r'年']
    LunarHolidayRegex = f'(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>除夕|春节|中秋节|中秋|元宵节|端午节|端午|重阳节)'
    HolidayRegexList1 = f'(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>新年|五一|劳动节|元旦节|元旦|愚人节|圣诞节|植树节|国庆节|情人节|教师节|儿童节|妇女节|青年节|建军节|女生节|光棍节|双十一|清明节|清明)'
    HolidayRegexList2 = f'(({DatePeriodYearRegex}|{DatePeriodYearInChineseRegex}|(?<yearrel>明年|今年|去年))(的)?)?(?<holiday>母亲节|父亲节|感恩节|万圣节)'
    SetUnitRegex = f'(?<unit>年|月|周|星期|日|天|小时|时|分钟|分|秒钟|秒)'
    SetEachUnitRegex = f'(?<each>(每个|每一|每)\\s*{SetUnitRegex})'
    SetEachPrefixRegex = f'(?<each>(每)\\s*$)'
    SetLastRegex = f'(?<last>last|this|next)'
    SetEachDayRegex = f'(每|每一)(天|日)\\s*$'
    TimeHourNumRegex = f'(00|01|02|03|04|05|06|07|08|09|0|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|1|2|3|4|5|6|7|8|9)'
    TimeMinuteNumRegex = f'(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)'
    TimeSecondNumRegex = f'(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|0|1|2|3|4|5|6|7|8|9)'
    TimeHourChsRegex = f'([零〇一二两三四五六七八九]|二十[一二三四]?|十[一二三四五六七八九]?)'
    TimeMinuteChsRegex = f'([二三四五]?十[一二三四五六七八九]?|六十|[零〇一二三四五六七八九])'
    TimeSecondChsRegex = f'{TimeMinuteChsRegex}'
    TimeClockDescRegex = f'(点\\s*整|点\\s*钟|点|时)'
    TimeMinuteDescRegex = f'(分钟|分|)'
    TimeSecondDescRegex = f'(秒钟|秒)'
    TimeBanHourPrefixRegex = f'(第)'
    TimeHourRegex = f'(?<!{TimeBanHourPrefixRegex})(?<hour>{TimeHourChsRegex}|{TimeHourNumRegex}){TimeClockDescRegex}'
    TimeMinuteRegex = f'(?<min>{TimeMinuteChsRegex}|{TimeMinuteNumRegex}){TimeMinuteDescRegex}'
    TimeSecondRegex = f'(?<sec>{TimeSecondChsRegex}|{TimeSecondNumRegex}){TimeSecondDescRegex}'
    TimeHalfRegex = f'(?<half>过半|半)'
    TimeQuarterRegex = f'(?<quarter>[一两二三四1-4])\\s*(刻钟|刻)'
    TimeChineseTimeRegex = f'{TimeHourRegex}({TimeQuarterRegex}|{TimeHalfRegex}|((过|又)?{TimeMinuteRegex})({TimeSecondRegex})?)?'
    TimeDigitTimeRegex = f'(?<hour>{TimeHourNumRegex}):(?<min>{TimeMinuteNumRegex})(:(?<sec>{TimeSecondNumRegex}))?'
    TimeDayDescRegex = f'(?<daydesc>凌晨|清晨|早上|早|上午|中午|下午|午后|晚上|夜里|夜晚|半夜|午夜|夜间|深夜|傍晚|晚)'
    TimeApproximateDescPreffixRegex = f'(大[约概]|差不多|可能|也许|约|不超过|不多[于过]|最[多长少]|少于|[超短长多]过|几乎要|将近|差点|快要|接近|至少|起码|超出|不到)'
    TimeApproximateDescSuffixRegex = f'(之前|以前|以后|以後|之后|之後|前|后|後|左右)'
    TimeRegexes1 = f'{TimeApproximateDescPreffixRegex}?{TimeDayDescRegex}?{TimeChineseTimeRegex}{TimeApproximateDescSuffixRegex}?'
    TimeRegexes2 = f'{TimeApproximateDescPreffixRegex}?{TimeDayDescRegex}?{TimeDigitTimeRegex}{TimeApproximateDescSuffixRegex}?(\\s*{AmPmDescRegex}?)'
    TimeRegexes3 = f'差{TimeMinuteRegex}{TimeChineseTimeRegex}'
    TimePeriodTimePeriodConnectWords = f'(起|至|到|–|-|—|~|～)'
    TimePeriodLeftChsTimeRegex = f'(从)?(?<left>{TimeDayDescRegex}?({TimeChineseTimeRegex}))'
    TimePeriodRightChsTimeRegex = f'{TimePeriodTimePeriodConnectWords}(?<right>{TimeDayDescRegex}?{TimeChineseTimeRegex})(之间)?'
    TimePeriodLeftDigitTimeRegex = f'(从)?(?<left>{TimeDayDescRegex}?({TimeDigitTimeRegex}))'
    TimePeriodRightDigitTimeRegex = f'{TimePeriodTimePeriodConnectWords}(?<right>{TimeDayDescRegex}?{TimeDigitTimeRegex})(之间)?'
    TimePeriodShortLeftChsTimeRegex = f'(从)?(?<left>{TimeDayDescRegex}?({TimeHourChsRegex}))'
    TimePeriodShortLeftDigitTimeRegex = f'(从)?(?<left>{TimeDayDescRegex}?({TimeHourNumRegex}))'
    TimePeriodRegexes1 = f'({TimePeriodLeftDigitTimeRegex}{TimePeriodRightDigitTimeRegex}|{TimePeriodLeftChsTimeRegex}{TimePeriodRightChsTimeRegex})'
    TimePeriodRegexes2 = f'({TimePeriodShortLeftDigitTimeRegex}{TimePeriodRightDigitTimeRegex}|{TimePeriodShortLeftChsTimeRegex}{TimePeriodRightChsTimeRegex})'
    ParserConfigurationBefore = f'(之前|以前|前)'
    ParserConfigurationAfter = f'(之后|之後|以后|以後|后|後)'
    ParserConfigurationUntil = f'(直到|直至|截至|截止(到)?)'
    ParserConfigurationSincePrefix = f'(自从|自|自打|打)'
    ParserConfigurationSinceSuffix = f'(以来|开始)'
    ParserConfigurationLastWeekDayToken = '最后一个'
    ParserConfigurationNextMonthToken = '下一个'
    ParserConfigurationLastMonthToken = '上一个'
    ParserConfigurationDatePrefix = ' '
    ParserConfigurationUnitMap = dict([(r'''年''', r'''Y'''),
                                       (r'''月''', r'''MON'''),
                                       (r'''个月''', r'''MON'''),
                                       (r'''日''', r'''D'''),
                                       (r'''周''', r'''W'''),
                                       (r'''天''', r'''D'''),
                                       (r'''小时''', r'''H'''),
                                       (r'''时''', r'''H'''),
                                       (r'''分钟''', r'''M'''),
                                       (r'''分''', r'''M'''),
                                       (r'''秒钟''', r'''S'''),
                                       (r'''秒''', r'''S'''),
                                       (r'''星期''', r'''W''')])
    ParserConfigurationUnitValueMap = dict([(r'''years''', 31536000),
                                            (r'''year''', 31536000),
                                            (r'''months''', 2592000),
                                            (r'''month''', 2592000),
                                            (r'''weeks''', 604800),
                                            (r'''week''', 604800),
                                            (r'''days''', 86400),
                                            (r'''day''', 86400),
                                            (r'''hours''', 3600),
                                            (r'''hour''', 3600),
                                            (r'''hrs''', 3600),
                                            (r'''hr''', 3600),
                                            (r'''h''', 3600),
                                            (r'''minutes''', 60),
                                            (r'''minute''', 60),
                                            (r'''mins''', 60),
                                            (r'''min''', 60),
                                            (r'''seconds''', 1),
                                            (r'''second''', 1),
                                            (r'''secs''', 1),
                                            (r'''sec''', 1)])
    ParserConfigurationSeasonMap = dict([(r'''春''', r'''SP'''),
                                         (r'''夏''', r'''SU'''),
                                         (r'''秋''', r'''FA'''),
                                         (r'''冬''', r'''WI''')])
    ParserConfigurationSeasonValueMap = dict([(r'''SP''', 3),
                                              (r'''SU''', 6),
                                              (r'''FA''', 9),
                                              (r'''WI''', 12)])
    ParserConfigurationCardinalMap = dict([(r'''一''', 1),
                                           (r'''二''', 2),
                                           (r'''三''', 3),
                                           (r'''四''', 4),
                                           (r'''五''', 5),
                                           (r'''1''', 1),
                                           (r'''2''', 2),
                                           (r'''3''', 3),
                                           (r'''4''', 4),
                                           (r'''5''', 5),
                                           (r'''第一个''', 1),
                                           (r'''第二个''', 2),
                                           (r'''第三个''', 3),
                                           (r'''第四个''', 4),
                                           (r'''第五个''', 5),
                                           (r'''第一''', 1),
                                           (r'''第二''', 2),
                                           (r'''第三''', 3),
                                           (r'''第四''', 4),
                                           (r'''第五''', 5)])
    ParserConfigurationDayOfMonth = dict([(r'''01''', 1),
                                          (r'''02''', 2),
                                          (r'''03''', 3),
                                          (r'''04''', 4),
                                          (r'''05''', 5),
                                          (r'''06''', 6),
                                          (r'''07''', 7),
                                          (r'''08''', 8),
                                          (r'''09''', 9),
                                          (r'''1''', 1),
                                          (r'''2''', 2),
                                          (r'''3''', 3),
                                          (r'''4''', 4),
                                          (r'''5''', 5),
                                          (r'''6''', 6),
                                          (r'''7''', 7),
                                          (r'''8''', 8),
                                          (r'''9''', 9),
                                          (r'''10''', 10),
                                          (r'''11''', 11),
                                          (r'''12''', 12),
                                          (r'''13''', 13),
                                          (r'''14''', 14),
                                          (r'''15''', 15),
                                          (r'''16''', 16),
                                          (r'''17''', 17),
                                          (r'''18''', 18),
                                          (r'''19''', 19),
                                          (r'''20''', 20),
                                          (r'''21''', 21),
                                          (r'''22''', 22),
                                          (r'''23''', 23),
                                          (r'''24''', 24),
                                          (r'''25''', 25),
                                          (r'''26''', 26),
                                          (r'''27''', 27),
                                          (r'''28''', 28),
                                          (r'''29''', 29),
                                          (r'''30''', 30),
                                          (r'''31''', 31),
                                          (r'''1日''', 1),
                                          (r'''2日''', 2),
                                          (r'''3日''', 3),
                                          (r'''4日''', 4),
                                          (r'''5日''', 5),
                                          (r'''6日''', 6),
                                          (r'''7日''', 7),
                                          (r'''8日''', 8),
                                          (r'''9日''', 9),
                                          (r'''10日''', 10),
                                          (r'''11日''', 11),
                                          (r'''12日''', 12),
                                          (r'''13日''', 13),
                                          (r'''14日''', 14),
                                          (r'''15日''', 15),
                                          (r'''16日''', 16),
                                          (r'''17日''', 17),
                                          (r'''18日''', 18),
                                          (r'''19日''', 19),
                                          (r'''20日''', 20),
                                          (r'''21日''', 21),
                                          (r'''22日''', 22),
                                          (r'''23日''', 23),
                                          (r'''24日''', 24),
                                          (r'''25日''', 25),
                                          (r'''26日''', 26),
                                          (r'''27日''', 27),
                                          (r'''28日''', 28),
                                          (r'''29日''', 29),
                                          (r'''30日''', 30),
                                          (r'''31日''', 31),
                                          (r'''一日''', 1),
                                          (r'''十一日''', 11),
                                          (r'''二十日''', 20),
                                          (r'''十日''', 10),
                                          (r'''二十一日''', 21),
                                          (r'''三十一日''', 31),
                                          (r'''二日''', 2),
                                          (r'''三日''', 3),
                                          (r'''四日''', 4),
                                          (r'''五日''', 5),
                                          (r'''六日''', 6),
                                          (r'''七日''', 7),
                                          (r'''八日''', 8),
                                          (r'''九日''', 9),
                                          (r'''十二日''', 12),
                                          (r'''十三日''', 13),
                                          (r'''十四日''', 14),
                                          (r'''十五日''', 15),
                                          (r'''十六日''', 16),
                                          (r'''十七日''', 17),
                                          (r'''十八日''', 18),
                                          (r'''十九日''', 19),
                                          (r'''二十二日''', 22),
                                          (r'''二十三日''', 23),
                                          (r'''二十四日''', 24),
                                          (r'''二十五日''', 25),
                                          (r'''二十六日''', 26),
                                          (r'''二十七日''', 27),
                                          (r'''二十八日''', 28),
                                          (r'''二十九日''', 29),
                                          (r'''三十日''', 30),
                                          (r'''1号''', 1),
                                          (r'''2号''', 2),
                                          (r'''3号''', 3),
                                          (r'''4号''', 4),
                                          (r'''5号''', 5),
                                          (r'''6号''', 6),
                                          (r'''7号''', 7),
                                          (r'''8号''', 8),
                                          (r'''9号''', 9),
                                          (r'''10号''', 10),
                                          (r'''11号''', 11),
                                          (r'''12号''', 12),
                                          (r'''13号''', 13),
                                          (r'''14号''', 14),
                                          (r'''15号''', 15),
                                          (r'''16号''', 16),
                                          (r'''17号''', 17),
                                          (r'''18号''', 18),
                                          (r'''19号''', 19),
                                          (r'''20号''', 20),
                                          (r'''21号''', 21),
                                          (r'''22号''', 22),
                                          (r'''23号''', 23),
                                          (r'''24号''', 24),
                                          (r'''25号''', 25),
                                          (r'''26号''', 26),
                                          (r'''27号''', 27),
                                          (r'''28号''', 28),
                                          (r'''29号''', 29),
                                          (r'''30号''', 30),
                                          (r'''31号''', 31),
                                          (r'''一号''', 1),
                                          (r'''十一号''', 11),
                                          (r'''二十号''', 20),
                                          (r'''十号''', 10),
                                          (r'''二十一号''', 21),
                                          (r'''三十一号''', 31),
                                          (r'''二号''', 2),
                                          (r'''三号''', 3),
                                          (r'''四号''', 4),
                                          (r'''五号''', 5),
                                          (r'''六号''', 6),
                                          (r'''七号''', 7),
                                          (r'''八号''', 8),
                                          (r'''九号''', 9),
                                          (r'''十二号''', 12),
                                          (r'''十三号''', 13),
                                          (r'''十四号''', 14),
                                          (r'''十五号''', 15),
                                          (r'''十六号''', 16),
                                          (r'''十七号''', 17),
                                          (r'''十八号''', 18),
                                          (r'''十九号''', 19),
                                          (r'''二十二号''', 22),
                                          (r'''二十三号''', 23),
                                          (r'''二十四号''', 24),
                                          (r'''二十五号''', 25),
                                          (r'''二十六号''', 26),
                                          (r'''二十七号''', 27),
                                          (r'''二十八号''', 28),
                                          (r'''二十九号''', 29),
                                          (r'''三十号''', 30),
                                          (r'''初一''', 32),
                                          (r'''三十''', 30),
                                          (r'''一''', 1),
                                          (r'''十一''', 11),
                                          (r'''二十''', 20),
                                          (r'''十''', 10),
                                          (r'''二十一''', 21),
                                          (r'''三十一''', 31),
                                          (r'''二''', 2),
                                          (r'''三''', 3),
                                          (r'''四''', 4),
                                          (r'''五''', 5),
                                          (r'''六''', 6),
                                          (r'''七''', 7),
                                          (r'''八''', 8),
                                          (r'''九''', 9),
                                          (r'''十二''', 12),
                                          (r'''十三''', 13),
                                          (r'''十四''', 14),
                                          (r'''十五''', 15),
                                          (r'''十六''', 16),
                                          (r'''十七''', 17),
                                          (r'''十八''', 18),
                                          (r'''十九''', 19),
                                          (r'''二十二''', 22),
                                          (r'''二十三''', 23),
                                          (r'''二十四''', 24),
                                          (r'''二十五''', 25),
                                          (r'''二十六''', 26),
                                          (r'''二十七''', 27),
                                          (r'''二十八''', 28),
                                          (r'''二十九''', 29)])
    ParserConfigurationDayOfWeek = dict([(r'''星期一''', 1),
                                         (r'''星期二''', 2),
                                         (r'''星期三''', 3),
                                         (r'''星期四''', 4),
                                         (r'''星期五''', 5),
                                         (r'''星期六''', 6),
                                         (r'''星期天''', 0),
                                         (r'''星期日''', 0),
                                         (r'''礼拜一''', 1),
                                         (r'''礼拜二''', 2),
                                         (r'''礼拜三''', 3),
                                         (r'''礼拜四''', 4),
                                         (r'''礼拜五''', 5),
                                         (r'''礼拜六''', 6),
                                         (r'''礼拜天''', 0),
                                         (r'''礼拜日''', 0),
                                         (r'''周一''', 1),
                                         (r'''周二''', 2),
                                         (r'''周三''', 3),
                                         (r'''周四''', 4),
                                         (r'''周五''', 5),
                                         (r'''周六''', 6),
                                         (r'''周日''', 0),
                                         (r'''周天''', 0),
                                         (r'''禮拜一''', 1),
                                         (r'''禮拜二''', 2),
                                         (r'''禮拜三''', 3),
                                         (r'''禮拜四''', 4),
                                         (r'''禮拜五''', 5),
                                         (r'''禮拜六''', 6),
                                         (r'''禮拜天''', 0),
                                         (r'''禮拜日''', 0),
                                         (r'''週一''', 1),
                                         (r'''週二''', 2),
                                         (r'''週三''', 3),
                                         (r'''週四''', 4),
                                         (r'''週五''', 5),
                                         (r'''週六''', 6),
                                         (r'''週日''', 0),
                                         (r'''週天''', 0)])
    ParserConfigurationMonthOfYear = dict([(r'''1''', 1),
                                           (r'''2''', 2),
                                           (r'''3''', 3),
                                           (r'''4''', 4),
                                           (r'''5''', 5),
                                           (r'''6''', 6),
                                           (r'''7''', 7),
                                           (r'''8''', 8),
                                           (r'''9''', 9),
                                           (r'''10''', 10),
                                           (r'''11''', 11),
                                           (r'''12''', 12),
                                           (r'''01''', 1),
                                           (r'''02''', 2),
                                           (r'''03''', 3),
                                           (r'''04''', 4),
                                           (r'''05''', 5),
                                           (r'''06''', 6),
                                           (r'''07''', 7),
                                           (r'''08''', 8),
                                           (r'''09''', 9),
                                           (r'''一月''', 1),
                                           (r'''二月''', 2),
                                           (r'''三月''', 3),
                                           (r'''四月''', 4),
                                           (r'''五月''', 5),
                                           (r'''六月''', 6),
                                           (r'''七月''', 7),
                                           (r'''八月''', 8),
                                           (r'''九月''', 9),
                                           (r'''十月''', 10),
                                           (r'''十一月''', 11),
                                           (r'''十二月''', 12),
                                           (r'''1月''', 1),
                                           (r'''2月''', 2),
                                           (r'''3月''', 3),
                                           (r'''4月''', 4),
                                           (r'''5月''', 5),
                                           (r'''6月''', 6),
                                           (r'''7月''', 7),
                                           (r'''8月''', 8),
                                           (r'''9月''', 9),
                                           (r'''10月''', 10),
                                           (r'''11月''', 11),
                                           (r'''12月''', 12),
                                           (r'''01月''', 1),
                                           (r'''02月''', 2),
                                           (r'''03月''', 3),
                                           (r'''04月''', 4),
                                           (r'''05月''', 5),
                                           (r'''06月''', 6),
                                           (r'''07月''', 7),
                                           (r'''08月''', 8),
                                           (r'''09月''', 9),
                                           (r'''正月''', 13),
                                           (r'''大年''', 13)])
    DateTimeSimpleAmRegex = f'(?<am>早|晨)'
    DateTimeSimplePmRegex = f'(?<pm>晚)'
    DateTimePeriodMORegex = f'(凌晨|清晨|早上|早|上午)'
    DateTimePeriodAFRegex = f'(中午|下午|午后|傍晚)'
    DateTimePeriodEVRegex = f'(晚上|夜里|夜晚|晚)'
    DateTimePeriodNIRegex = f'(半夜|夜间|深夜)'
    DurationUnitValueMap = dict([(r'''Y''', 31536000),
                                 (r'''Mon''', 2592000),
                                 (r'''W''', 604800),
                                 (r'''D''', 86400),
                                 (r'''H''', 3600),
                                 (r'''M''', 60),
                                 (r'''S''', 1)])
    HolidayNoFixedTimex = dict([(r'''父亲节''', r'''-06-WXX-6-3'''),
                                (r'''母亲节''', r'''-05-WXX-7-2'''),
                                (r'''感恩节''', r'''-11-WXX-4-4''')])
    MergedBeforeRegex = f'(前|之前)$'
    MergedAfterRegex = f'(后|後|之后|之後)$'
    TimeNumberDictionary = dict([('''零''', 0),
                                 ('''一''', 1),
                                 ('''二''', 2),
                                 ('''三''', 3),
                                 ('''四''', 4),
                                 ('''五''', 5),
                                 ('''六''', 6),
                                 ('''七''', 7),
                                 ('''八''', 8),
                                 ('''九''', 9),
                                 ('''〇''', 0),
                                 ('''两''', 2),
                                 ('''十''', 10)])
    TimeLowBoundDesc = dict([(r'''中午''', 11),
                             (r'''下午''', 12),
                             (r'''午后''', 12),
                             (r'''晚上''', 18),
                             (r'''夜里''', 18),
                             (r'''夜晚''', 18),
                             (r'''夜间''', 18),
                             (r'''深夜''', 18),
                             (r'''傍晚''', 18),
                             (r'''晚''', 18),
                             (r'''pm''', 12)])
    DefaultLanguageFallback = 'DMY'
    MorningTermList = [r'上午']
    AfternoonTermList = [r'下午']
    EveningTermList = [r'晚上']
    DaytimeTermList = [r'白天']
    NightTermList = [r'深夜']
# pylint: enable=line-too-long
